version: '3.8'

services:
  web:
    build: .
    container_name: php-app
    volumes:
      - ./php:/var/www/html/php
      - ./public:/var/www/html
      - ./default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8800:80"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    external: true  # since network is created outside compose
